%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-tf2
Version:        0.41.6
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS tf2 package

License:        BSD
URL:            http://www.ros.org/wiki/tf2
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-builtin-interfaces
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-rcutils
Requires:       ros-kilted-rosidl-runtime-cpp
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-ros
BuildRequires:  ros-kilted-builtin-interfaces
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-rcutils
BuildRequires:  ros-kilted-rosidl-runtime-cpp
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-cmake-copyright
BuildRequires:  ros-kilted-ament-cmake-cppcheck
BuildRequires:  ros-kilted-ament-cmake-cpplint
BuildRequires:  ros-kilted-ament-cmake-google-benchmark
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-cmake-lint-cmake
BuildRequires:  ros-kilted-ament-cmake-uncrustify
BuildRequires:  ros-kilted-ament-cmake-xmllint
%endif

%description
tf2 is the second generation of the transform library, which lets the user keep
track of multiple coordinate frames over time. tf2 maintains the relationship
between coordinate frames in a tree structure buffered in time, and lets the
user transform points, vectors, etc between any two coordinate frames at any
desired point in time.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Thu Dec 18 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.6-1
- Autogenerated by Bloom

* Fri Nov 28 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.5-1
- Autogenerated by Bloom

* Fri Nov 07 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.4-1
- Autogenerated by Bloom

* Fri Oct 17 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.3-3
- Autogenerated by Bloom

* Fri Oct 17 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.3-2
- Autogenerated by Bloom

* Fri Oct 17 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.3-1
- Autogenerated by Bloom

* Thu Jul 24 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.2-1
- Autogenerated by Bloom

* Mon Jun 23 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.1-1
- Autogenerated by Bloom

* Fri Apr 25 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.41.0-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.40.1-2
- Autogenerated by Bloom

* Wed Jan 15 2025 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.40.1-1
- Autogenerated by Bloom

* Fri Dec 20 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.40.0-1
- Autogenerated by Bloom

* Mon Nov 25 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.39.3-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.39.2-1
- Autogenerated by Bloom

* Tue Oct 15 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.39.1-1
- Autogenerated by Bloom

* Thu Oct 03 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.39.0-1
- Autogenerated by Bloom

* Fri Jul 19 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.38.2-1
- Autogenerated by Bloom

* Tue Jul 09 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.38.1-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.38.0-1
- Autogenerated by Bloom

* Wed May 29 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.37.1-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.37.0-1
- Autogenerated by Bloom

* Wed Apr 10 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.36.2-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.36.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Alejandro Hernandez Cordero <alejandro@openrobotics.org> - 0.36.0-2
- Autogenerated by Bloom

