%{?!ros_distro:%global ros_distro humble}
%global pkg_name tf2_tools
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-humble-tf2-tools
Version:        0.25.23
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://www.ros.org/wiki/tf2_tools
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
tf2_tools


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
tf2_tools


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
tf2_tools


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Mon Sep 07 2026 Chris Lalancette <clalancette@openrobotics.org> - 0.25.23-1
- Autogenerated by Bloom

* Tue Jul 28 2026 Chris Lalancette <clalancette@openrobotics.org> - 0.25.22-1
- Autogenerated by Bloom

* Tue Jul 14 2026 Chris Lalancette <clalancette@openrobotics.org> - 0.25.21-1
- Autogenerated by Bloom
